### ISSUE TITLE
api returning bad data 

### ISSUE THREAD

**Issue by jonlundy** [jesusha123/airthings-exporter#2]
The api started throwing errors today 

Log file:

```
Traceback (most recent call last):
  File "/usr/local/bin/airthings-exporter", line 5, in <module>
    from airthings.main import main
  File "/usr/local/lib/python3.11/site-packages/airthings/main.py", line 14, in <module>
    REGISTRY.register(CloudCollector(args.client_id, args.client_secret, args.device_id))
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/registry.py", line 40, in register
    names = self._get_names(collector)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/registry.py", line 80, in _get_names
    for metric in desc_func():
  File "/usr/local/lib/python3.11/site-packages/airthings/CloudCollector.py", line 22, in collect
    data = self.__get_device_samples__(access_token, device_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airthings/CloudCollector.py", line 64, in __get_device_samples__
    data = response.json()['data']
           ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

```

**Comment by jesusha123** [comment]
@jonlundy , did it ever work? Some of the most likely issues are the parameters being wrong, or you're exceeding the scraping quota. Last time I checked you can only issue 120 requests per hour.

As you can guess, I did not add comprehensive error checking and reporting.

Can you issue a token and test the API on the command line to make sure everything is working? Perhaps you'll see the error you're facing on the API response. You can also try the cURL commands below (replace client id, client secret, device id and access token:

```shell
# Generate token, grab access_token from here

curl --location 'https://accounts-api.airthings.com/v1/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id=INSERT_CLIENT_ID' \
--data-urlencode 'client_secret=INSERT_CLIENT_SECRET' \
--data-urlencode 'scope=read:device:current_values'

# Send request

curl --location 'https://ext-api.airthings.com/v1/devices/INSERT_DEVICE_ID/latest-samples' \
--header 'Authorization: Bearer INSERT_ACCESS_TOKEN'
```
